[target.armv7-linux-androideabi]
linker = "d:/prog/android_sdk_godot/ndk/23.2.8568313/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi29-clang.cmd"

[target.aarch64-linux-android]
linker = "d:/prog/android_sdk_godot/ndk/23.2.8568313/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android29-clang.cmd"

[target.i686-linux-android]
linker = "d:/prog/android_sdk_godot/ndk/23.2.8568313/toolchains/llvm/prebuilt/windows-x86_64/bin/i686-linux-android29-clang.cmd"

[target.x86_64-linux-android]
linker = "d:/prog/android_sdk_godot/ndk/23.2.8568313/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android29-clang.cmd"
